### ISSUE TITLE
K8s API

### ISSUE THREAD

**Issue by mlahlouh** [mabumusa1/saas#66]
Client SDK:
`https://kubernetes.io/docs/reference/using-api/client-libraries/
`
K8s Endpoint: http://dev.steercampaign.com:8001/api/v1/namespaces/

to get pods:
`curl http://dev.steercampaign.com:8001/api/v1/namespaces/default/pods
`
create new deployment of nginx
```
curl -X POST -H 'Content-Type: application/yaml' --data '
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80
' http://dev.steercampaign.com:8001/apis/apps/v1/namespaces/default/deployments
```
